# Generated by Django 3.2.6 on 2021-08-26 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 8, 26, 20, 33, 25, 719706))),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 8, 26, 20, 33, 25, 719706))),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('priceRecovered', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 8, 26, 20, 33, 25, 720706))),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.unit'),
        ),
    ]
