# Generated by Django 3.2.6 on 2021-08-26 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 20, 33, 33, 798905)),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 20, 33, 33, 799905)),
        ),
        migrations.AlterField(
            model_name='unit',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 20, 33, 33, 798905)),
        ),
    ]
