# Generated by Django 3.2.6 on 2021-08-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ManyToManyField(null=True, to='ims.ItemType'),
        ),
    ]
