# Generated by Django 3.2.6 on 2021-08-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_auto_20210827_0052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
