# Generated by Django 3.2.6 on 2021-08-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0008_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['product']},
        ),
    ]
