# Generated by Django 3.2.6 on 2021-08-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0011_auto_20210827_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.CharField(max_length=245, null=True),
        ),
    ]
