# Generated by Django 3.2.6 on 2021-08-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_attendance_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Friday', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='attendance_choice',
            field=models.CharField(default='Present', max_length=100),
        ),
    ]
