# Generated by Django 3.2.6 on 2021-08-27 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_attendance_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 23, 49, 23, 492766), null=True),
        ),
    ]
